In [1]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
import numpy as np

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
vocab_size = 10000

In [6]:
one_hot_rep = [one_hot(words, vocab_size) for words in sent]

In [7]:
one_hot_rep

[[7956, 3491, 9800, 1014],
 [7956, 3491, 9800, 7077],
 [7956, 3011, 9800, 3982],
 [1068, 513, 9775, 3635, 8905],
 [1068, 513, 9775, 3635, 4327],
 [4729, 7956, 9219, 9800, 8147],
 [4847, 322, 4413, 3635]]

In [8]:
seq_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen=seq_length)
embedded_docs

array([[   0,    0,    0,    0, 7956, 3491, 9800, 1014],
       [   0,    0,    0,    0, 7956, 3491, 9800, 7077],
       [   0,    0,    0,    0, 7956, 3011, 9800, 3982],
       [   0,    0,    0, 1068,  513, 9775, 3635, 8905],
       [   0,    0,    0, 1068,  513, 9775, 3635, 4327],
       [   0,    0,    0, 4729, 7956, 9219, 9800, 8147],
       [   0,    0,    0,    0, 4847,  322, 4413, 3635]], dtype=int32)

In [9]:
# feature representation
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length = seq_length))
model.compile('adam', 'mse')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 111ms/step


array([[[ 4.20953296e-02, -2.76085492e-02, -2.91746389e-02,
          1.97810642e-02,  2.22693756e-03,  2.33387239e-02,
          2.15007700e-02, -4.65133451e-02, -4.16012630e-02,
          3.62404920e-02],
        [ 4.20953296e-02, -2.76085492e-02, -2.91746389e-02,
          1.97810642e-02,  2.22693756e-03,  2.33387239e-02,
          2.15007700e-02, -4.65133451e-02, -4.16012630e-02,
          3.62404920e-02],
        [ 4.20953296e-02, -2.76085492e-02, -2.91746389e-02,
          1.97810642e-02,  2.22693756e-03,  2.33387239e-02,
          2.15007700e-02, -4.65133451e-02, -4.16012630e-02,
          3.62404920e-02],
        [ 4.20953296e-02, -2.76085492e-02, -2.91746389e-02,
          1.97810642e-02,  2.22693756e-03,  2.33387239e-02,
          2.15007700e-02, -4.65133451e-02, -4.16012630e-02,
          3.62404920e-02],
        [-1.03806965e-02, -3.65212448e-02, -2.29176171e-02,
          2.42318846e-02, -1.54898055e-02, -3.80808115e-03,
          2.87317075e-02,  7.09167868e-03, -3.734829

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 7956, 3491, 9800, 1014], dtype=int32)

In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 32ms/step


array([[ 0.04209533, -0.02760855, -0.02917464,  0.01978106,  0.00222694,
         0.02333872,  0.02150077, -0.04651335, -0.04160126,  0.03624049],
       [ 0.04209533, -0.02760855, -0.02917464,  0.01978106,  0.00222694,
         0.02333872,  0.02150077, -0.04651335, -0.04160126,  0.03624049],
       [ 0.04209533, -0.02760855, -0.02917464,  0.01978106,  0.00222694,
         0.02333872,  0.02150077, -0.04651335, -0.04160126,  0.03624049],
       [ 0.04209533, -0.02760855, -0.02917464,  0.01978106,  0.00222694,
         0.02333872,  0.02150077, -0.04651335, -0.04160126,  0.03624049],
       [-0.0103807 , -0.03652124, -0.02291762,  0.02423188, -0.01548981,
        -0.00380808,  0.02873171,  0.00709168, -0.03734829, -0.04961808],
       [ 0.02915399,  0.00422804, -0.00740229, -0.01382715, -0.04522065,
         0.01966728, -0.01380664, -0.04466666,  0.04967603, -0.00323166],
       [ 0.03042724, -0.03382105,  0.02675026, -0.00337978, -0.01776342,
         0.02751755,  0.021232  , -0.04833069